# Generated by Django 5.2.5 on 2025-09-06 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishingTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(choices=[('AT', 'Austria'), ('BE', 'Belgium'), ('PL', 'Poland'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('ES', 'Spain'), ('SE', 'Sweden'), ('UA', 'Ukraine'), ('GB', 'United Kingdom'), ('US', 'United States')], default='UA', max_length=2)),
                ('date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_type', models.CharField(max_length=45)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('fishing_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='api.fishingtrip')),
            ],
        ),
    ]
