# Generated by Django 5.2.5 on 2025-09-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='catches/'),
        ),
    ]
