# Generated by Django 5.2.5 on 2025-10-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_catch_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, help_text='Quantity of fish'),
        ),
    ]
