# Generated by Django 5.2.5 on 2025-10-03 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_catch_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Fish type',
                'verbose_name_plural': 'Fish types',
            },
        ),
        migrations.AlterField(
            model_name='catch',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='catch',
            name='fish_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='api.fishtype'),
        ),
    ]
