# Generated by Django 5.2.5 on 2025-10-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fishtype_alter_catch_weight_alter_catch_fish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, help_text='Quantity of fish'),
        ),
    ]
