services:
  migrate:
    image: fishing_register
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py migrate --noinput
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: db
    restart: "no"

  app:
    image: fishing_register
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      DEBUG: "False"
      SECRET_KEY: "${SECRET_KEY}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: db
    restart: unless-stopped

  db:
    image: postgres:17.7
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: